pipeline{
    agent any 
    scm checkout
    stages{
        stage (build){
            steps{
                sh '''
                echo "Building the project..."
                '''
            }
        }
    }
}