pipeline{
    agent any 
    scm checkout
    stages{
        stage (build){
            steps{
                sh '''
                echo "Building the project..."
                '''
            }
            steps(building docker image){
                sh '''
                docker login -u "$DOCKER_USER" -p 
                cd /home/usr/project 
                '''         
            }
        }
    }
}