pipeline{
    agents none
    stages{
        stage ("build"){
            agent{
                docker {
                    image 'node:20-alpine'
                }
                steps{
                    sh 'node --version'
                }
            }
        }
    }
}}